version: "3"

networks:
  monitor:

services:
  demo-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "./logs/:/opt/logs/"
    networks:
      - monitor

  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090"
    networks:
      - monitor
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    volumes:
      - "./loki_config.yml:/etc/loki/local-config.yaml"
    command: "-config.file=/etc/loki/local-config.yaml"
    networks:
      - monitor

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - "./logs/:/opt/logs/"
      - "./promtail_config.yml:/etc/promtail/config.yml"
    command: "-config.file=/etc/promtail/config.yml"
    networks:
      - monitor

  grafana:
    image: grafana/grafana:10.0.0
    ports:
      - "3000:3000"
    depends_on:
      - loki
      - prometheus
    networks:
      - monitor
    volumes:
      - "./grafana/datasources/:/etc/grafana/provisioning/datasources/"

  agent:
    build: 
      context: ..
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - demo-app
      - prometheus
      - loki
    networks:
      - monitor
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
      - LOKI_URL=http://loki:3100 