server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: demo-app
    static_configs:
      - targets:
          - demo-app
        labels:
          job: demo-app
          __path__: /opt/logs/*log 