version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN:-demo-mode}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN:-demo-mode}
      - PROMETHEUS_URL=${PROMETHEUS_URL:-http://prometheus:9090}
      - LOKI_URL=http://loki:3100
      - LLM_PROVIDER=${LLM_PROVIDER:-openai}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - prometheus
      - loki
    volumes:
      - ./app:/app/app
    networks:
      - sherlog-network
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "container_name=sherlog-app"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - sherlog-network
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "container_name=redis"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./demo/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - sherlog-network
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "container_name=prometheus"

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - sherlog-network
    volumes:
      - ./demo/loki:/etc/loki

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./demo/promtail:/etc/promtail
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - sherlog-network
    depends_on:
      - loki

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - sherlog-network
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "container_name=node-exporter"

  sample-app:
    build: 
      context: ./demo/sample-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - sherlog-network
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "container_name=sample-app"

networks:
  sherlog-network:
    driver: bridge

volumes:
  prometheus_data: {} 