services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - PROMETHEUS_URL=${PROMETHEUS_URL}
      - LLM_PROVIDER=${LLM_PROVIDER:-openai}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ./app:/app/app
    networks:
      - sherlog-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - sherlog-network

networks:
  sherlog-network:
    driver: bridge 