server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    pipeline_stages:
      - docker: {}
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log

  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*log

  # Add specific configuration for our sample app
  - job_name: sample-app
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            timestamp: timestamp
    static_configs:
      - targets:
          - localhost
        labels:
          job: sample-app
          app: sample-app
          __path__: /var/lib/docker/containers/*/*-json.log 